import Head from 'next/head'
import Buttons from '../components/Buttons'
import Buttons2 from '../components/Buttons2'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Free Tailwindcss and Nextjs UI Elments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex container mx-auto flex-col w-full justify-center items-center">
      <h1 className='text-4xl mt-32 mb-12 font-bold'>Free Tailwindcss and Nextjs UI Elments</h1>
      <h1 className="h-16 w-full text-center border-b-2 shadow-md 
     py-6 mx-auto justify-center text-2xl font-bold my-5 bg-gray-200">
        Buttons</h1>

       <Buttons />

       <Buttons2 />
      </main>

     
    </div>
  )
}
